### ISSUE TITLE
Injury calculation

### ISSUE THREAD

**Issue by markotainio** [ITHIM/ITHIM-R#9] opened 2018-02-01 09:53 UTC
Discussion on new injury calculation method. To be discussed in ITHIM-R meeting on 8th of February.

@robj411

**Comment by robj411** [comment] 2018-02-07 13:30
In the talk on the 8th February, I plan to present and discuss the plan for the injury module in ITHIM-R. The presentation can be found here: [https://www.overleaf.com/read/kbghyxqxgnxd#/52828747/](url). You can view online, or download with the 'PDF' button.

The main topic for discussion is how the user provides data.  So far, these are my questions:

1) Do we require the user to supply distance-travelled data, in addition to those provided for the creation of the synthetic population?
2) Age-group discussion. Here are some options:
  2.1 We choose groupings and insist on them
  2.2 We choose groupings, allow the user to supply data as they wish and then manipulate into our groupings
  2.3 We allow the user to choose groupings
  2.4 We use whatever the user supplies
  2.5 We choose adaptively
3) What would be a good input format?

The bulk of the work in ITHIM-R is (a) making injury predictions based on past data and (b) translating these into health costs.

The method for (a) is negative-binomial regression. The method for (b) is an open question and I'd welcome your input on that, in addition to the questions around user-provided data.

**Comment by gotom22** [comment] 2018-02-08 16:08
questions re crash attributes:
- roadway type

**Comment by gotom22** [comment] 2018-02-08 16:16
How to consider safety-in-number in the model structure?

**Comment by gotom22** [comment] 2018-02-08 16:26
Specifications of user data requirements:
- matching data stratification

Aim to use same distance data as rest of tool (i.e. synth. pop. data)

**Comment by gotom22** [comment] 2018-02-08 16:50
could it be fitted without actual distance value? (just in relative terms)

**Comment by robj411** [comment] 2018-02-09 16:02
I have added a relative term to the "no/other/unknown vehicle" injury model.

I've called it R_x, and it performs the function of A_m in the collision model: recall that A_m is the distance travelled for mode m. Here, R_x is the relative abundance of hazard x. R_x=1 for all x in the baseline. R_x=1.1 in the scenario means the abundance of the hazard increases 10%.

This way we can model changes in distance travelled, without actually knowing any distances travelled, or who travelled them.

**Comment by gotom22** [comment] 2018-03-01 14:49
suggestion to expand road type stratification to include "off-road facilities, ie. bike ped only parks, trails, etc."

**Comment by robj411** [comment] 2018-03-16 18:41
Here is a plan for how the injury module will function. (tbi=to be implemented)

**Data inputs**

There will be two or three inputs.
1. The first input comes directly from the synthetic population. It will be a data frame with known headers, and it will detail all the travel done by each demographic group by each mode. (tbi when we have agreed (a) what the synthetic population looks like and (b) what the processed version looks like. The processed version might be used also by pollution and noise modules.) There are multiple versions of this input: one per scenario (where the baseline counts as one scenario).
2. The second input is an injury data set. This will likely be a spreadsheet or Rdata (tbi) object with prespecified column and row names. Row names will be ICD-10 codes. Column headers will be multivariate and will specify the covariates.
3. (tbi) The optional data input is a set of additional data that aren't captured in the synthetic population, e.g. bus and HGV driving. Perhaps also other covariates like road type can be covered here.

**Optional user inputs**

There will be optional user inputs, such as which model type to use, which age groups to use if the model is large (tbi). The user can also upload previously saved models.

**Functionality**

The first step (tbi) will be to check that the inputs make sense, and to bounce back to the user if they don't. The next step (tbi) is data harmonisation, e.g. if there are different age groupings in the distance and injury datasets.

Two models run in parallel: (a) one for collisions, where we have data relating to striking vehicles, and (b) one for no/other/unknown vehicle, for any injuries that are caused by things without drivers we could model.

If the datasets are small, the module tries all possible models for each of (a) and (b) and chooses the best in terms of AIC. If datasets are larger, we try a subset of possible models (tbi).

The 'predict' function generates predicted injury numbers for each input of type 1, i.e. one per scenario. 

**Output** 

The output is a set of arrays (one per scenario) of all injuries caused, according to the covariates supplied in the inputs. These will be handed to a GBD calculator (tbi). 

Users can save models as they go along.

**To-do list** 

1. Find a few example datasets
2. Generalise engine to accommodate any conceivable dataset combination
3. Fix the form of the processed synthetic population
4. Choose way to build model for larger datasets
5. What to do if data are fatality only
6. Accommodate additional distance dataset
7. What to do if there are e.g. bus distance data but not HGV
8. V00 code
9. Add parameter for underreporting
10. Think about safety in numbers

**Comment by JDWoodcock** [comment] 2018-03-30 11:09
thanks please start filling in the wiki https://github.com/ITHIM/ITHIM-R/wiki/Tool-architecture 
@robj411

**Comment by gotom22** [comment] 2018-04-23 11:08
@robj411 
Hi Rob
this issue could use some sorting out/closure...
- you could digest in a new comment into a list of specific tasks (- [ ] see edited comment above) or id some specific new issues (which need further disucussion)...or a mix of both. Also consider moving conclusions to Wiki.

...then we could close this.

**Comment by JDWoodcock** [comment] 2018-04-23 18:03
on the thinking about list if we estimates should be informed by data from other settings. For example I would expect relative rates per mile/hour by age group to be similar across settings. As we get event and exposure data for more settings this can be tested.
Re 'any conceivable datasets' that sound quite challenging. I suggest we work on the top few most likely for now!

**Comment by robj411** [comment] 2018-05-24 13:49
Safety-in-numbers to-do list:
- [] Choose distributions for all values
- [] Decide how the user can edit them
- [] Decide to what unit they apply
- [] Make provision for user to supply their unit of analysis, and correct equations accordingly
- [] Sort out quantile conflict when the exposure is less than 1

**Closed** 2019-02-18 17:35 UTC
Labels: 1 Data Sources, 3 Data Harmonization, 8B Impact Calculation Injuries, Injury
